#PUMP_LOG = "cache/pumplog.json"
#CHARGE_LOG = "cache/chargelog.json"
PI_FAN_LOG = "/home/pi/greenhouse/pi_fanlog.json"
PUMP_LOG = "/home/pi/greenhouse/pumplog.json"
SYSCONFIG = "/home/pi/greenhouse/config.json"
SERVICE_LOG = "/home/pi/greenhouse/servicelog.json"

PUMP_GPIO = 4
PUMP_RUNTIME = 10
PUMP_RUN_INTERVAL = 43000 # Slightly less than 1/2 day

PI_FAN_GPIO = 5
HEATPAD_GPIO = 7
LIGHTS_GPIO = 1
GREENHOUSE_FAN_GPIO = 6

PI_TEMP_POLL_INTERVAL = 60
PI_TEMP_UPPER_LIMIT = 45
PI_TEMP_COOLDOWN = 35

GREENHOUSE_TEMP_POLL_INTERVAL = 60
GREENHOUSE_FAN_DAYTIME_UPPER_LIMIT = 29
GREENHOUSE_FAN_DAYTIME_LOWER_LIMIT = 28
GREENHOUSE_FAN_NIGHTTIME_UPPER_LIMIT = 22
GREENHOUSE_FAN_NIGHTTIME_LOWER_LIMIT = 21

HEATPAD_DAYTIME_UPPER_LIMIT = 28
HEATPAD_DAYTIME_LOWER_LIMIT = 27
HEATPAD_NIGHTTIME_UPPER_LIMIT = 20
HEATPAD_NIGHTTIME_LOWER_LIMIT = 19

daytimeStart = '08:00:00'
daytimeEnd   = '22:00:00'




#CHARGER_GPIO = 2
#CHARGER_RUNTIME = 10800 # 3 Hours
#CHARGER_OFFTIME = 10800 # 3 Hours
